# Generated by Django 4.2.4 on 2023-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
