# Generated by Django 4.2.4 on 2023-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tasks_category_alter_tasks_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='client',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=30),
        ),
    ]
